### ISSUE TITLE
models/index.js code style

### ISSUE THREAD

**Issue by tgaff** [adamrobertreid/project_03#2]
```js
module.exports = {
  User: require('./user'), Trail: require('./trail')
};
```

It's easier to read this if you put each key on a separate line.  If you had more than 3 models you'd have to do this anyway or have too much on one line:

```js
module.exports = {
  User: require('./user'), 
  Trail: require('./trail')
};
```

**Comment by adamrobertreid** [comment]
Hey, Travis,
Thanks for pointing that out. I'll make that correction!
